trigger:
  -master

pool:
  vmImage: 'windows-latest'

steps:
- task: HugoTask@1
  inputs:
    source: 
    destination: '$(System.DefaultWorkingDirectory)/public'

- task: PublishBuildArtifacts@1
  inputs:
  targetPath:'$(System.DefaultWorkingDirectory)/public'
  artifact: ''
  publishLocation: 'pipeline'