trigger:

- master

pool:
  vmImage: 'windows-latest'

steps:
- task: HugoTask@1
  inputs:
    source: 
    destination: '$(System.DefaultWorkingDirectory)/public'

- task: PublishPipelineArtifact@1
  inputs:
    targetPath: '$(System.DefaultWorkingDirectory)/public'
    publishLocation: 'pipeline'
