baseURL = "https://estefaniavargas.github.io"
languageCode = "en-us"
title = "My New Hugo Site"
theme = "vertical_nav"
relativeURLs = true


[outputs]
  home = ["HTML", "JSON"]

[params]
  custom_css = ["/css/vertical-nav/layouts.css", 
                "/css/vertical-nav/menus.css", 
                "/css/vertical-nav/lists.css", 
                "/css/vertical-nav/shortcodes.css"
                ]

[menu]
  [[menu.main]]
    identifier = "home"
    name = "Principal"
    url = "/"
    weight = 1

  [[menu.main]]
    identifier = "documentacion"
    name = "Documentación"
    url = "/documentacion"
    weight = 2
    
  [[menu.main]]
    identifier = "extra"
    name = "Extra"
    url = "/extra"
    weight = 3

  [[menu.main]]
    identifier = "hugo"
    name = "Hugo"
    url = "/hugo"
    weight = 4




