baseURL = "https://estefaniavargas.github.io"
languageCode = "en-us"
title = "My New Hugo Site"
theme= "bancolombia-doc"
relativeURLs= true

[outputs]
  home = ["HTML", "JSON"]

[menu]
  [[menu.main]]
    name = "Home"
    url = "/"
    weight = 1

  [[menu.main]]
    name = "Documentacion"
    url = "/documentacion/"
    weight = 2
    
    [[menu.main]]
    name = "Extra"
    url = "/extra/"
    weight = 3
